config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index', as: :dashboards
resources :dashboards, only: [:get, :update, :edit, :post, :create, :show, :new, :index]
resources :logins, only:[:new, :create]

resources :registrations, only:[:new, :create, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  # scope :test, -> (len) {where("LENGTH(title) > ?", len)}
  # scope :author_of, -> (var) { where(user_id: ?, var) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :password, presence: true

    has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    
    @blog = Blog.all
  end

  def edit
    session[:blog_id] = params[:id]
    @blog = Blog.find_by(id: params[:id])
    @user = User.find_by(id: session[:user_id])
    

    
    if @blog.user_id != @user.id
      flash[:alert] = "You are not the author of that blog"
      redirect_to dashboards_path
    end

      
  end

  def post
  end

  def show
    @user = User.find_by(id: session[:user_id])
    @blog = Blog.find_by(id: params[:id])
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(dash_params)
    @user = User.find_by(id: session[:user_id])
    @blog.user = @user


    if @blog.save     
      redirect_to dashboard_path(@blog)
    else
      flash[:alert] = "couldn't create blog"
      render :new, status: :unprocessable_entity
    end
  
  end  

  def update
    @user = User.find_by(id: session[:user_id])
    @blog = Blog.find_by(id: session[:blog_id])
    if @blog.update(params.require(:blog).permit(:title, :blog))
      flash[:alert] = "Blog updated succesfully"
      redirect_to dashboards_path
    else
      flash[:alert] = "Blog not updated succesfully"
      render :edit, status: :unprocessable_entity

    end
  end

  private
    def dash_params
      params.require(:blog).permit(:title, :blog)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
    #so that the view form can have the correct model
    @user = User.new 
    #notice the change between this part and dashboard's
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user
  end

  def create
    @user = User.find_by(login_params)
    session[:user_id] = @user.id
    if @user
      redirect_to dashboards_path
    else
      flash[:alert] = "Email or password is wrong"
      render :new, status: :unprocessable_entity
    end
  end

  private
    def login_params
      params.require(:user).permit(:email, :password)
    end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
    user = User.find_by(id: session[:user_id])
    redirect_to dashboards_path if user

  end

  def index
    @blog = Blog.all

  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "couldn't save the user" 
      render :new ,status: :unprocessable_entity
    end
  end
  private 
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/edit.html.erb
<h1>Edit article</h1>


<%= form_with model: @blog, url: dashboards_path do |f| %>
    <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p>
  
    <p>
      <%= f.label :blog %><br/>
      <%= f.text_area :blog %>
    </p>
  
    <p>
        <%= f.submit :"submit" %>
    </p>
<% end %>
<%= link_to "Back To Blog Index", dashboards_path%>

app/views/dashboards/index.html.erb
<h1>Welcome</h1>
<p>Below are all of the blogs</p>
<p>Find me in app/views/dashboards/index.html.erb</p>

<table>
    <thead>
        <tr>
        <th><strong>Author</strong></th>
        <th><strong>Blog</strong></th>
        <th colspan="3"><strong>Blog Number</strong></th>

        <th colspan="3"><strong>Action</strong></th>

        </tr>
    </thead>


    <tbody>
        <%= @blog.each do |test| %>
        <tr>
            <td> <%= User.find_by(id: test.user_id).email %>
            <td> <%= test.blog %>
            <td> <%= test.id %>
            


        </tr>
        <% end %>
    </tbody>
</table>

app/views/dashboards/new.html.erb
<h1> Create Blog</h1>


<%= form_with model: Blog, url: "/dashboards" do |f| %>
    <p>
      <%= f.label :title %><br/>
      <%= f.text_field :title %>
    </p>
  
    <p>
      <%= f.label :blog %><br/>
      <%= f.text_area :blog %>
    </p>
  
    <p>
      <%= f.submit :"submit" %>
    </p>
<% end %>

app/views/dashboards/show.html.erb
<h1>Blog Details</h1>

<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>


<table>
    <thead>
        <tr>
        <th><strong> Title: </strong> </th>
        <th><strong> Blog: </strong>  </th>
        <th><strong> Author: </strong> </th>
        <th><strong> Date Published: </strong> </th>
        <th><strong> Date Updated: </strong> </th>

        <th><strong> Article ID: </strong> </th>


        </tr>
    </thead>


    <tbody>
        <tr>
            <td> <%= @blog.title %>
            <td> <%= @blog.blog %>
            <td> <%= User.find_by(id: @blog.user_id).email %>
            <td > <%= @blog.created_at %>
            <td> <%= @blog.updated_at %>

            <td> <%= @blog.id %>

        </tr>
    </tbody>
</table>

<%= link_to "Back To Blog Index", dashboards_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPractice</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div> <%= notice %> </div>
    <div> <%= alert %> </div>

    <%= yield %>
  </body>
</html>

app/views/logins/create.html.erb
<h1>Logins#create</h1>
<p>Find me in app/views/logins/create.html.erb</p>

app/views/logins/new.html.erb
<h1>Log In</h1>
<p>Find me in app/views/registrations/new.html.erb</p>
<%=form_with model: User, url: logins_path do |form|%>
    <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
    </div>
    <div>
        <%=form.label :password %>
        <%= form.password_field :password %>
    </div>
    <div>
    <%= form.submit :"log in" %>
    </div>
<% end %>